version: '3.7'
services:
  db:
    container_name: db
    image: "mysql/mysql-server:8.0.26"
    restart: always
    environment:
      MYSQL_DATABASE: SMSDb
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_USER: john
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_HOST: 172.*.*.*
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    # expose:
    #   - "3306"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # expose:
    #   - "8080"
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./SMSender.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ConnectionStrings__SMSDb: server=db;port=3306;user=john;password=passw0rd;database=SMSDb;charset=utf8;
      ASPNETCORE_Rabbit__Host: rabbitmq
      ASPNETCORE_Rabbit_User: guest
      ASPNETCORE_Rabbit_Password: guest 
    volumes:
      - ./logs/api:/app/logs
    depends_on: 
      - db
    links: 
      - db
    ports:
      - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    entrypoint: ["/app/wait-for.sh", "db:3306", "--"]
    command: ["dotnet", "SMSender.Api.dll"]
  processor:
    container_name: processor
    build:
      context: ./
      dockerfile: ./SMSender.Processor/Dockerfile
    environment:
      ASPNETCORE_ConnectionStrings__SMSDb: server=db;port=3306;user=john;password=passw0rd;database=SMSDb;charset=utf8;
      ASPNETCORE_Rabbit__Host: rabbitmq
      ASPNETCORE_Rabbit_User: guest
      ASPNETCORE_Rabbit_Password: guest 
    volumes:
      - ./logs/api:/app/logs
    depends_on: 
      - db
    links: 
      - db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    entrypoint: ["/app/wait-for.sh", "db:3306", "--"]
    command: ["dotnet", "SMSender.Processor.dll"]
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
  # front:
  #   container_name: front
  #   image: "nginx:alpine"
  #   ports: 
  #     - "80:80"
  #   volumes:
  #     #- ./Frontend/build:/usr/share/nginx/html
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   logging:
  #     options:
  #       max-size: "10m"
  #       max-file: "10"